shortcut_model_name2full_model_name = {"llama-2-7b-chat":"meta-llama/Llama-2-7b-chat",
                                       "llama-2-7b-chat-hf":"meta-llama/Llama-2-7b-chat-hf",
                                       "vicuna-7b-v1.5":"lmsys/vicuna-7b-v1.5",
                                       "Mistral-7B-Instruct-v0.2":"mistralai/Mistral-7B-Instruct-v0.2",
                                       "falcon-7b-instruct":"tiiuae/falcon-7b-instruct"}

prompts = {
            "selection":{
                        "zero_shot": """Question: select the most suitable meaning for '{word}' in the following sentence: {text}\nChoose the corresponding definition among: \n{candidate_definitions}.\nAnswer by reporting the corresponding definition and do not motivate your answer. Answer:""",
                        "one_shot": """Question: select the most suitable meaning for "floor" in the following sentence: they needed rugs to cover the bare floors. Choose the corresponding definition among: \n0) the inside lower horizontal surface (as of a room, hallway, tent, or other structure);\n1) a structure consisting of a room or set of rooms at a single position along a vertical scale;\n2) a lower limit;\n3) the ground on which people and animals move about;\n4) the bottom surface of any lake or other body of water;\n5) the lower inside surface of any hollow structure;\n6) the occupants of a floor;\n7) the parliamentary right to address an assembly;\n8) the legislative hall where members debate and vote and conduct other business;\n9) a large room in a exchange where the trading is done;\nAnswer by reporting the corresponding definition and do not motivate your answer. Answer: 0) the inside lower horizontal surface (as of a room, hallway, tent, or other structure);\nQuestion: select the most suitable meaning for "{word}" in the following sentence: {text}\nChoose the corresponding definition among: \n{candidate_definitions}. \nAnswer by reporting the corresponding definition and do not motivate your answer. Answer:""",
                        "few_shot": """Question: select the most suitable meaning for "computer" in the following sentence: I am using a computer for the creation of 3-D models. Choose the corresponding definition among: \n0) a machine for performing calculations automatically;\n1) an expert at calculation (or at operating calculating machines);\nAnswer by reporting the corresponding definition and do not motivate your answer. Answer: 0) a machine for performing calculations automatically;\nQuestion: select the most suitable meaning for "great" in the following sentence: a great delay. Choose the corresponding definition among: \n0) relatively large in size or number or extent; larger than others of its kind;\n1) of major significance or importance;\n2) remarkable or out of the ordinary in degree or magnitude or effect;\n3) very good;\n4) uppercase;\n5) in an advanced stage of pregnancy;\nAnswer by reporting the corresponding definition and do not motivate your answer. Answer: 0) relatively large in size or number or extent; larger than others of its kind;\nQuestion: select the most suitable meaning for "eat" in the following sentence: What did you eat for dinner last night? Choose the corresponding definition among: 0) take in solid food;\n1) eat a meal; take a meal;\n2) take in food; used of animals only;\n3) worry or cause anxiety in a persistent way;\n4) cause to deteriorate due to the action of water, air, or an acid;\nAnswer by reporting the corresponding definition and do not motivate your answer. Answer: 0) take in solid food;\nQuestion: select the most suitable meaning for "{word}" in the following sentence: {text}\nChoose the corresponding definition among:\n{candidate_definitions}.\nAnswer by reporting the corresponding definition and do not motivate your answer. Answer:"""
                       },
            "generation":{
                        "zero_shot": """Question: define the meaning of "{word}" in the following sentence: {text} Provide a definition which identifies the meaning of "{word}" in the context provided and do not motivate your answer. Answer:""",
                        "one_shot": """Question: define the meaning of "floor" in the following sentence: they needed rugs to cover the bare floors. Provide a definition which identifies the meaning of "floor" in the context provided and do not motivate your answer. Answer: the inside lower horizontal surface (as of a room, hallway, tent, or other structure).\nQuestion: define the meaning of "{word}" in the following sentence: {text}. Provide a definition which identifies the meaning of "{word}" in the context provided and do not motivate your answer. Answer:""",
                        "few_shot": """Question: define the meaning of "computer" in the following sentence: I am using a computer for the creation of 3-D models. Provide a definition which identifies the meaning of "computer" in the context provided and do not motivate your answer. Answer: a machine for performing calculations automatically. Question: define the meaning of "great" in the following sentence: a great delay. Provide a definition which identifies the meaning of "great" in the context provided and do not motivate your answer. Answer: relatively large in size or number or extent; larger than others of its kind. Question: define the meaning of "eat" in the following sentence: What did you eat for dinner last night? Provide a definition which identifies the meaning of "eat" in the context provided and do not motivate your answer. Answer: take in solid food.\nQuestion: define the meaning of "{word}" in the following sentence: {text} Provide a definition which identifies the meaning of "{word}" in the context provided and do not motivate your answer. Answer:""",
                       }
          }
